### ISSUE TITLE
assume https scheme if a bare domain is entered

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/IndieAuth.com#119]
If only a domain is entered, then assume https scheme. 

Provide a nice error message if indieauth.com can't connect to the website.

See https://github.com/indiecert/auth/issues/21 for more background.

**Comment by singpolyma** [comment]
Could also fallback to http if can't connect.  Though https really should be a requirement for auth

**Comment by paulcmal** [comment]
Authentication should just fail without TLS support. If authentication is allowed over plain unencrypted HTTP, then indieauth.com is not really an authentication but an identity theft provider.

It's now super easy to setup an HTTPS cert with Let's Encrypt (or any other free certificate authority implementing the ACME protocol). There is little to no reason to allow unencrypted access to your website, and even less so to allow for unencrypted authentication.

If anybody needs help setting up HTTPS on their website, I'm willing to help :)

Also, it's worth nothing that most authentication providers may not work as expected when authenticating over HTTP on usually-HTTPS site, as silos rel=me links will point to the HTTPS version ([example](https://indieauth.com/auth?me=cmal.info&client_id=https%3A%2F%2Findieauth.com&redirect_uri=https%3A%2F%2Findieauth.com%2Fsuccess)).

**Comment by voxpelli** [comment]
One reason: GitHub Pages

While it should be strongly recommended that https should be used, banning http would both be a breaking change and cause unnecessary pains.

"Be conservative in what you send, be liberal in what you accept" – enable people to start easy and then progressively enhance into something more hardened.

**Comment by paulcmal** [comment]
> start easy and then progressively enhance into something more hardened

In my experience, that's definitely not how it works. Having organized IT and privacy/security workshops with mostly non-tech people, I have come to believe you simply cannot − for the vast majority of users − add a security layer.

Security needs to be embedded within the system, and not as an option you can do without.

This being said, after a short discussion with @aaronpk on IRC, I changed my mind (not regarding security considerations in general, but this use-case in particular) as the main concern is, as always with the IndieWeb community : you need to be able to run it on any hosting provider (even one that REALLY SUCKS).

To be honest, I think that's a strategic nightmare and something that should be reconsidered, but being a broader IndieWeb policy it should not be discussed here.

> If only a domain is entered, then assume https scheme.

In the end, this sounds like a decent solution. @aaronpk, would indieauth.com be able to implement HTTP Strict Transport Security (HSTS) and such so that once a connection has been established on HTTPS (for instance, by default when just providing the bare domain name), it cannot revert back to plaintext HTTP?

I think this would be a good compromise:
* non-HTTPS users would still be able to login (although that still sounds TERRIBLY BAD)
* HTTPS users can login, and once they do, they can't login anymore via plaintext HTTP

**Comment by aaronpk** [comment]
> HTTPS users can login, and once they do, they can't login anymore via plaintext HTTP (if their server supports HSTS).

Interesting idea, although I'm not sure how practical that is. indieauth.com is actually run on multiple backend servers which do not share a database or even share any state. There isn't actually any permanent storage built in to the implementation, as everything necessary is discovered each time the person enters their URL. 

Each server does its own caching of the rel=me links found on the URL, which is why when you come back a second time the list loads faster, although it's explicitly implemented as a cache rather than a permanent storage.

What I'm getting at is there is currently no mechanism to permanently store any information about a domain, much less share that information between each backend server, so I'm not sure the best way to implement that.
