### ISSUE TITLE
Fails based on content type when checking Link headers

### ISSUE THREAD

**Issue by rhiaro** [aaronpk/IndieAuth.com#126]
`rel="me"` discovery works okay (probably because of caching), but after I click a provider to sign in indieauth.com errors with:

> Unknown error retrieving http://rhiaro.co.uk/: The URL http://rhiaro.co.uk/ returned an invalid content-type: 'application/ld+json'

My site returns json-ld by default if no `Accept` header is sent. I think you should probably send a `text/html` accept header when indieauth.com makes the request if that's what's required. But even so, if it's only parsing the `Link` headers for the endpoints it shouldn't care about the content-type of the body at this point.

**Comment by aaronpk** [comment]
Thanks! I updated indieauth.com to send a text/html Accept header. 

This was failing because when you sign in, it re-checks your website to find the rel=me link and that was failing because of the non-html response. The initial page load returns from the cache so you were correct, and if you had clicked "re-scan" that would have failed.
