### ISSUE TITLE
Check for "IndieAuth:" header in redirects

### ISSUE THREAD

**Issue by cweiske** [aaronpk/IndieAuth.com#129]
# Problem

When a client accessed the withknown's indieauth endpoint and was not logged in, it immediately redirected to known's normal login. This  means that the `IndieAuth: authorization_endpoint` header was sent along with the `Location` redirect header.
But the final login form did not contain that header, because it's a completely separate part of withknown. So indieauth.com would not see the indieauth header at all, and thus telling the user that the header is missing.
# Proposal

IndieAuth clients should also check for the `IndieAuth` header in redirects, too - not only in the final response.

This will require a change in the IndieAuth.com software and in the IndieAuth specification.

---

Related to #93 and Idno/known#1499.

**Comment by sebilasse** [comment]
@redaktor [consider above for IndieAuth node.js clone]

Feature Request
---
How about also sending an `IndieAuth: client_id` header to "me" to support lndieAuth logging ?

**Comment by aaronpk** [comment]
Some discussion this week led us to the conclusion that this header is not actually necessary. The logic was that if a user links to an authorization endpoint with an HTML `<link>` tag, then we can assume it supports the protocol because the link is present. The main reason I had added the check for the header in the first place was that I didn't want to present a button to the user that would fail if they clicked on it. If they are choosing to delegate to an authorization endpoint, there is no need for it to pre-acknowledge that it's an authorization endpoint.
