### ISSUE TITLE
describe obtaining an Access Token on /developers

### ISSUE THREAD

**Issue by sebsel** [aaronpk/IndieAuth.com#133]
[IndieAuth.com/developers](https://indieauth.com/developers) is currently only describing how to let people to log-in to a site, but now that we got Micropub, we might also need a guide on how to obtain an access token.

The information is on [Indieweb.org](https://indieweb.org/obtaining-an-access-token) too, so maybe just grab it from there?

**Comment by aaronpk** [comment]
This is part of the now years-long confusion between indieauth.com the service for developers and indieauth.com the service for users. I actually explicitly don't want to mention obtaining an access token on the developers page, since I believe that would further the confusion. You should only be reading the developers page if you are doing login only, and not getting an access token. In this case, indieauth.com is abstracting away the mf2 parsing and relmeauth verification for you. If you want an access token, you're going to need to parse the user's website for the `rel="token_endpoint"` and ``rel="authorization_endpoint"` and do those steps yourself. Does that make sense?
