### ISSUE TITLE
Try https when there's no scheme specified

### ISSUE THREAD

**Issue by gjedeer** [aaronpk/IndieAuth.com#136]
I just tried to log in to the IndieWeb wiki by entering "gdr.name" in the login box. It failed because my Github profile links back to "https://gdr.name/", not "http://gdr.name/".

In the age of LetsEncrypt, maybe it's a reasonable strategy to try HTTPS and fall back to HTTP when the user did not supply a scheme? Or maybe check if the link back is to the same domain only with a different URL scheme?

**Comment by aaronpk** [comment]
If you redirect http://gdr.name/ to https://gdr.name/ then this will work as expected.

**Comment by gjedeer** [comment]
Okay, feel free to close if you think this use case is not worth fixing.

**Comment by aaronpk** [comment]
Well I think it might be time to default to https when just the domain is entered, but that's already filed in #119, so I'll close this as a duplicate. In any case, you'll continue to have problems one way or another if you don't redirect http -> https since they appear to be two different websites without the redirect. Thanks!
