### ISSUE TITLE
"The authentication provider replied with an error: csrf_detected"

### ISSUE THREAD

**Issue by rrrnld** [aaronpk/IndieAuth.com#213]
Hi :)

When trying to login via Github I get the above error. The page I'm using for auth is https://arne.schlueter.is, the service I'm trying to log in to is https://uberspace.de/en/ (you can create a free account for debugging purpopses, but I'm also happy to provide any useful informtion).

Thanks for developing and maintaining this, it's by far the nicest way to use OpenID for me.

**Comment by aaronpk** [comment]
Try using `https://indieauth.com/openid` instead, I need to update the docs for that.

**Comment by heyarne** [comment]
Can you elaborate please? I set up my web page using the instruction the instructions on the page you linked, the relevant parts of which are (in my case):
```html
<!DOCTYPE html>
<html lang="en">
   <head>
        <!-- … -->
        <link rel="openid.delegate" href="https://arne.schlueter.is">
        <link rel="openid.server" href="https://openid.indieauth.com/openid">
        <!-- … -->
    </head>
    <body>
        <!-- … -->
        <li><label>Github</label> active as <a rel="me" href="https://github.com/heyarne">heyarne</a></li>
        <li><label>PGP Public Key</label> <a rel="pgpkey" href="/key.txt">6264E016</a></li>
	<!-- … -->
    </body>
</html>
```

Do you mean to say I should swap the `href` in `<link rel="openid.server" href="https://openid.indieauth.com/openid">` with the URL you posted?

**Comment by aaronpk** [comment]
Yes exactly, change https://openid.indieauth.com/openid to https://indieauth.com/openid

if that works I'll make sure to update the instructions

**Comment by heyarne** [comment]
Thanks! Trying to login where the problem originally occured, I saw that
the `redirect_uri` is still set to https://openid.indieauth.com. This
results in a different error ("Missing OpenID session data"). I could
however succesfully authenticate on https://indieauth.com, where the
`redirect_uri` was correctly set to `https://indieauth.com/…`. Maybe a
caching problem lead it to still use the previous URL?

**Comment by lukasbestle** [comment]
I was having the exact same issue (funnily also at Uberspace, seems to be one of the few remaining sites that implement OpenID...). The change from `openid.indieauth.com` to just `indieauth.com` fixed it for me.

**Comment by lukasbestle** [comment]
@aaronpk I ran into the issue with the incorrect `redirect_uri` and that was unfortunately very hard to debug:

I still had an old session cookie on `openid.indieauth.com`, so the authentication seemingly succeeded, but then triggered an error at the service I was logging in to because of the expired challenge timestamp.

Basically the issue was: On the way in the auth session gets set on `indieauth.com`, but on the way out it gets retrieved on `openid.indieauth.com`. This will make all logins fail – either directly on IndieAuth.com ("Missing OpenID session data") or on the site of the service (incorrect/expired auth data).

So two steps to fix OpenID login on IndieAuth.com:

- Always populate the `redirect_uri` query param with the actual subdomain that is used (depending on how the user has configured their `openid.server`). This makes OpenID logins work for all cases again.
- Update the instructions to use this markup:

```html
<link rel="openid.delegate" href="https://example.com/" />
<link rel="openid.server" href="https://indieauth.com/openid" />
```
