### ISSUE TITLE
Accept URLs to other (valid) providers in provider's profile

### ISSUE THREAD

**Issue by blueyed** [aaronpk/IndieAuth.com#87]
I am not sure, but when the Twitter provider is available (and links to your site), it should be good if the Github profile would link to the Twitter profile (instead of to your site).

This way I could still use the Twitter URL in my Github profile.

**Comment by aaronpk** [comment]
While I believe this is technically true, it would end up adding a lot of complexity to the code, and I don't think it would be very useful. If you are already linking your Twitter account to your website, then you can just use Twitter as the provider when signing in. If you are using Twitter and another method like [GPG auth](https://indieauth.com/gpg) or email/SMS auth, then there isn't a lot of reason to add Github.

If you really do want to use Github to sign in, then I think it's actually a good thing that it requires you to add your website to your Github profile, since your website should be where your tweet-like content lives anyway.

**Comment by blueyed** [comment]
I see and agree.

Thanks for your explanation, and the pointer to the GPG method - very nice.

IndieAuth.com made Google's OpenID 2.0 Shutdown really less painful, and it's such a nice approach!
Thanks!
